{% set name = "scikit-digital-health" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PfizerRD/{{ name }}/archive/{{ version }}.tar.gz
  sha256: cc45d0b786fd31329cae1c44d069d869bb5cd7c6961cb3edb1f95fc0e23dd730

build:
  number: 0
  # script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - pkg-config
  host:
    - python
    - pip
    - numpy
    - meson-python
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.12.0
    - pandas >=1.0.0
    - lightgbm >=2.3.0
    - pywavelets
    - scikit-learn
    - h5py
    - matplotlib-base
    - packaging
    - pyyaml
    - importlib_metadata  # [py<38]

test:
  imports:
    - skdh
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PfizerRD/scikit-digital-health
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scikit Digital Health (SKDH) is a Python package with methods for ingesting and analyzing wearable inertial sensor data.
  doc_url: https://scikit-digital-health.readthedocs.io
  dev_url: https://github.com/PfizerRD/scikit-digital-health

extra:
  recipe-maintainers:
    - LukasAdamowicz
